### ISSUE TITLE
Addition of box drawing characters, gradients, etc.

### ISSUE THREAD

**Issue by ix** [lucy/tewi-font#19]
My choice of terminal (suckless st) doesn't seem to have box drawing characters (e.g. `toilet -f future` or gradient chars (██▓▒░), and I like this font quite a bit.

The only two fonts which I've seen that provide these characters are leggie (except without the characters for `toilet -f future`), and Metis.

It'd be quite nice if they were added to Tewi.

**Comment by sshbio** [comment]
One of the reason why I use tewi is because it has a nice support for these semigraphic characters (box drawing and blocks), with perfect alignment, etc.

I also use st, and have problems with these characters only when they are bold.  Otherwise, they look good:

![2016-03-17-194742_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/13857274/7ce50d8e-ec79-11e5-998f-25af9139fd0e.png)

The font substitution may pick bold characters in other fonts where they are available in bold instead of using non-bold tewi versions.

Maybe copy-pasting these problematic characters in gbdfed could fix that issue...

**Comment by ix** [comment]
They don't show up for me at all.

**Comment by lucy** [comment]
your setup is broken

**Comment by ix** [comment]
welp
